id: PBDD55D8B
initial_creation_type: input
source_metadata:
  title: Do Khyentse Yeshe Dorje Series
  language: nl
  description: 'A series of texts associated with the treasure-revealer Do Khyentse
    Yeshe Dorje (mdo mkhyen brtse ye shes rdo rje, 1800–1866), renowned as the ''mind
    emanation'' of Jigme Lingpa:'
  volume:
    9d7df213b8a24abbaebfeeec45773dff:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Aspiration Prayers
    7a211da848f245579f2eb5c848374f37:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    629fd89636ef4ec0b114e414530100a2:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Guru Rinpoche Prayers
    b6e01492e4bb4d9bbb8cb14cf4450c32:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Guru Rinpoche Prayers
    760a664948f747a995ee9e1bf56aee98:
      title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
      parent: Lineage Prayers
    ec212b6850ea4c1b9ad621f806102ee8:
      title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and
        Liberation of Rigdzin Jalü Dorje'
      parent: Prayers
    8523be6ce3074f46a35968982f3a4b0e:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Preliminaries
created_at: '2022-02-28T22:55:15.001264'
last_modified_at: '2022-02-28T22:55:15.001267'
